services:
  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: http://server:9090
    depends_on:
      - server

  server:
    build: ./server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    environment:
      TZ: Asia/Yekaterinburg
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Yekaterinburg"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
    depends_on:
      - db

  db:
    image: postgres:16.1
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
